spring:
  boot:
    admin:
      client:
        username: root
        password: root
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      rabbit:
        enabled: true
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: 192.168.1.88
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS