server:
  port: 7902

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.88:3306/mycloud_tmp2
      username: root
      password: root.hunter
      stat-view-servlet:
        enabled: true
      filters: mergeStat
      use-global-data-source-stat: true


seata:
  client:
    enabled: true
    application-id: ${spting.application.name}
    tx-service-group: mycloud-tx-group
    undo:
      log-table: undo_log
  registry:
    type: eureka
    eureka:
      service-url: http://localhost:8761/eureka
      application: ${spting.application.name}
  store:
    mode: db
    db:
      driver-class-name: com.mysql.jdbc.Driver
      datasource: druid
      db-type: mysql
      url: jdbc:mysql://192.168.1.88:3306/mycloud_tmp2
      user: root
      password: root.hunter
  service:
    vgroup_mapping.mycloud-tx-group: mycloud-seata
    disableGlobalTransaction: false
    enableDegrade: false
    default.grouplist: 127.0.0.1:8091