server:
  port: 7801

spring:
  security:
    user:
      name: root
      password: root
  boot:
    admin:
      discovery:
        enabled: true
      client:
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}