server:
  port: 7901

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.88:3306/mycloud_tmp1
      username: root
      password: root.hunter
      stat-view-servlet:
        enabled: true
      filters: mergeStat
      use-global-data-source-stat: true
  cloud:
    alibaba:
      seata:
        tx-service-group: mycloud-tx-group
seata:
  client:
    undo:
      log-table: undo_log
  registry:
    type: eureka
    eureka:
      service-url: http://localhost:8761/eureka
  store:
    mode: db
    db:
      driver-class-name: com.mysql.jdbc.Driver
      datasource: druid
      db-type: mysql
      url: jdbc:mysql://192.168.1.88:3306/mycloud_tmp1
      user: root
      password: root.hunter
  service:
    vgroup_mapping.mycloud-tx-group: mycloud-seata-tc
    disableGlobalTransaction: false
    enableDegrade: false
    mycloud-seata-tc.grouplist: 127.0.0.1:8091
